title: Sreehari Radhakrishnan
email: sreehari.rk1@gmail.com
phone: +91 9567943603
description: Cinematographer based in Kerala. A graduate of the prestigious Satyajit Ray Film and Television Institute. I love images as much as I love storytelling. Natural light and vintage lenses fascinate me. I am a good listener and a keen observer!
baseurl: ""
url: "https://sreehari-radhakrishnan.github.io"
instagram_username: "etcetera.__"
