title: Sreehari Radhakrishnan
email: sreehari.rk1@gmail.com
phone: +91 9567943603
description: Cinematographer based in Kerala. A graduate of the prestigious Satyajit Ray Film and Television Institute, I bring a strong foundation in both technical expertise and artistic vision to every project I undertake.
baseurl: ""
url: "https://sreehari-radhakrishnan.github.io"
instagram_username: "etcetera.__"